### ISSUE TITLE
 Add a normal error description if the response from the server is empty

### ISSUE THREAD

**Issue by egorprnn** [Richienb/slothpixel#2]
At the moment, if the API does not give any response, for example, if it does not work, then we get an error: `TypeError: Cannot read property 'json' of undefined.`

This error does not tell us anything, you need to add a normal description of the error, for example: `No response was received from the server`.

**Comment by Richienb** [comment]
Fixed in https://github.com/Richienb/slothpixel/commit/f14d0506de48fb0c768f0e67560cdc55e532b551, published as [`v1.2.1`](https://github.com/Richienb/slothpixel/releases/tag/v1.2.1).
